annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: add new needed values for plausible 2.1.0
    - kind: fixed
      description: fix templating of extraEnv
apiVersion: v2
appVersion: v2.1.0
dependencies:
  - condition: clickhouse.enabled
    name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.9.0
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.12.10
description: A Helm Chart for Plausible Analytics - a simple and privacy-friendly alternative to Google Analytics
home: https://plausible.io/
icon: https://plausible.io/docs/img/favicon.png
keywords:
  - plausible analytics
  - analytics
maintainers:
  - name: zekker6
    email: zekker6@gmail.com
    url: https://github.com/zekker6/
name: plausible-analytics
sources:
  - https://github.com/zekker6/helm-charts/tree/main/charts/apps/plausible-analytics
  - https://hub.docker.com/r/plausible/analytics
  - https://github.com/plausible/analytics
type: application
version: 0.2.1
